# Copyright © 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT
---

- name: Register the current govc version (if any)
  command: govc version
  ignore_errors: yes
  register: govc_version_found
  changed_when: false

- block:

  - name: Download archive 32 bits
    get_url:
      url: "{{govc_download_url}}/govc_{{ ansible_system|lower }}_386.gz"
      dest: "{{govc_tmp}}/govc-{{govc_version}}.gz"
      validate_certs: no
    when: "'32' in ansible_architecture"

  - name: Download archive 64 bits
    get_url:
      url: "{{govc_download_url}}/govc_{{ ansible_system|lower }}_amd64.gz"
      dest: "{{govc_tmp}}/govc-{{govc_version}}.gz"
      validate_certs: no
    when: "'64' in ansible_architecture"

  - name: uncompress govc binary
    command: "gunzip {{govc_tmp}}/govc-{{govc_version}}.gz"
    args:
      creates: "{{govc_tmp}}/govc-{{govc_version}}"

  - name: move govc into place
    command: mv "{{govc_tmp}}/govc-{{govc_version}}" "{{govc_file}}"

  - name: ensure govc executable
    file:
      path: "{{govc_file}}"
      mode: 0755

  when: "govc_version_found|failed or govc_version not in govc_version_found.stdout"
